### ISSUE TITLE
Losing saved videos

### ISSUE THREAD

**Issue by Elmers-1st-son** [puppe/resumeLater#21]
I saved several videos in firefox with resumelater. I ran Advanced System Optimizer, to clean up junk files and optimize the registry. My save list is now empty. Where did they go? Where are the data kept? Can I stop the cleanup from removing my saved data?

**Comment by puppe** [comment]
The data is stored somewhere in your Firefox profile. Here is how you can find your profile: <https://support.mozilla.org/en-US/kb/profiles-where-firefox-stores-user-data#w_how-do-i-find-my-profile>

I do not know whether you can recover you data after Advanced System Optimizer "optimized" your system. You should ask their support.

In my opinion, tools like that do more harm than good.
