### ISSUE TITLE
Don't open a new tab with full web page for the UI

### ISSUE THREAD

**Issue by FSMaxB** [puppe/resumeLater#22]
It would be much nicer if clicking the extensions icon would not open a new tab but display the UI as a drawer (or however this is called) like many other addons do.

**Comment by puppe** [comment]
Many other add-ons, like ad blockers or script blockers, interact with the current page. It makes sense for those add-ons to open the UI in a popup. That way the user can interact with the add-on while still having the context of the current page.

resumeLater's list of videos does not interact with the current page. Therefore I chose to open the list in a new tab. Users can interact with the page like they can with any other page. They can move the page to another window, and they can open links in the same tab or in a new tab. Overall, I think it is more versatile.

I am not very likely to change this behavior nor to accept any pull requests that change it. However, I would be interested why you would prefer the UI opening in a popup. What do you think would be the advantages over opening it in a new tab? Why do you think the disadvantages would be acceptable? Maybe I am missing something.

**Comment by FSMaxB** [comment]
For me it doesn't really make sense to have it occupy an entire tab, because almost all interactions with the addon require only one interaction without any followup action. So there is just no need to open it up in a tab.

As it stands, if I want to watch a video, I have to open the extension, click on the video, watch it, then when I'm done, either search the tab where the extension was or open a new one, delete the video and then close the one (or two) extension tab(s) again.

In contrast to just clicking on the extension icon and then deleting the video.

I also don't think it makes sense to have more than one place to interact with the addon (like multiple tabs).

The most annoying thing is that I have to either open new tabs and close them later or always find the tab where I opened the extension instead of having just one place where I interact with it and it closes automatically.

**Comment by FSMaxB** [comment]
I also don't think that it needs to occupy an entire window. If I don't want to watch a video but just take a look at what Videos are in the list, I don't want it to distract it from my workflow by taking over the entire screen and requiring me to close it again.

**Comment by FSMaxB** [comment]
One example of an AddOn that is quite similar to yours and also uses a drawer for its UI is [BrowseLater](https://addons.mozilla.org/en-US/firefox/addon/browselater/).

**Comment by puppe** [comment]
[OneTab](https://addons.mozilla.org/de/firefox/addon/onetab/) is somewhat similar to BrowseLater, and it uses a tab for its UI.

But I gather from your comments that you are overwhelmed with too many tabs. When resumeLater opens in a new tab it makes you uncomfortable because that is one more tab to keep track of. At the same time, you do not always know whether you have it open already in another tab.

Do you think the situation could be improved if resumeLater would only open a new tab if the UI is not already displayed in another tab in the same window? If there is already a tab open, a click on the button would instead bring that tab into focus. Once you close that tab, you can be sure that there is no other tab with the resumeLater UI.

**Comment by FSMaxB** [comment]
That would certainly be an improvement!

**Comment by FSMaxB** [comment]
But what it doesn't fix from my perspective is the workflow of just taking a quick look at the list of videos and then continuing what I was doing.

**Comment by FSMaxB** [comment]
Do you feel there is a benefit to having the UI in a tab?

**Comment by puppe** [comment]
Having the UI in a tab has the following (non-exhaustive list of) advantages:

* It works equally well on all screen sizes and resolutions without some complicated logic for adjusting the size of the pop-up.
* Users can zoom in or out like they can on any other web page. Think the font is too small or too large? Just zoom.
* Users can search the page (Ctrl+F or Cmd+F) like any other web page.

**Comment by FSMaxB** [comment]
The last point can be solved by implementing a search bar. But I understand the reasoning now. Although I still think that it would be worth it to put in that extra effort, although I won't be the one to do it or maintain it, so it's easy for me to say.

Anyway, thanks for this discussion and for providing this extension in the first place!

And I think making sure that only one tab is opened is a good improvement either way.

**Comment by puppe** [comment]
Thank you very much for your feedback! I still think it is better to keep the UI in its own tab, but I have opened a new issue (#23) regarding the improvement discussed here.
